// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	JoinedTsMillis       int64    `protobuf:"varint,2,opt,name=joined_ts_millis,json=joinedTsMillis,proto3" json:"joined_ts_millis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetJoinedTsMillis() int64 {
	if m != nil {
		return m.JoinedTsMillis
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "com.rotemtam.User")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0x0b, 0x82, 0x40,
	0x14, 0xc0, 0x71, 0xac, 0x88, 0x3c, 0x2a, 0xc2, 0x49, 0x68, 0x91, 0x22, 0x70, 0xd2, 0xa1, 0x6f,
	0xd0, 0x6e, 0x83, 0xd4, 0xd2, 0x22, 0x77, 0xe7, 0xcb, 0x2e, 0xee, 0xf9, 0xe4, 0xde, 0xf3, 0xfb,
	0x47, 0x46, 0xeb, 0x6f, 0xf9, 0xff, 0xd5, 0x06, 0x81, 0x59, 0x77, 0x50, 0x0c, 0x81, 0x84, 0x92,
	0xb5, 0x25, 0x2c, 0x02, 0x09, 0xa0, 0x68, 0x3c, 0x54, 0x6a, 0x71, 0x67, 0x08, 0xc9, 0x5e, 0xc5,
	0x23, 0x43, 0x68, 0x7a, 0x8d, 0x90, 0x46, 0x59, 0x94, 0xc7, 0xf5, 0xea, 0x0b, 0x57, 0x8d, 0x90,
	0xe4, 0x6a, 0xf7, 0x26, 0xd7, 0x43, 0xdb, 0x08, 0x37, 0xe8, 0xbc, 0x77, 0x9c, 0xce, 0xb2, 0x28,
	0x9f, 0xd7, 0xdb, 0x9f, 0xdf, 0xb8, 0x9a, 0xf4, 0x72, 0x7a, 0x1c, 0x3b, 0x27, 0xaf, 0xd1, 0x14,
	0x96, 0xb0, 0xfc, 0x57, 0xca, 0xc1, 0x04, 0x78, 0x7a, 0xb0, 0x52, 0x22, 0xb5, 0xe0, 0xcd, 0x72,
	0x5a, 0x39, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x97, 0xe8, 0x58, 0x9b, 0x00, 0x00, 0x00,
}
